### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by vydarenyj** [pkourany/RGBmatrixPanel_IDE#11]
Hi i have isue with this can you help me please ? Thanks

Arduino: 1.8.6 (Windows 7), Vývojová deska: "Arduino/Genuino Uno"

testshapes_16x32:25:14: error: 'D6' was not declared in this scope

  #define CLK D6

              ^

C:\Users\vydaja\Downloads\RGBmatrixPanel_IDE-master\RGBmatrixPanel_IDE-master\examples\testshapes_16x32\testshapes_16x32.ino:45:32: note: in expansion of macro 'CLK'

 RGBmatrixPanel matrix(A, B, C, CLK, LAT, OE, false);

                                ^

testshapes_16x32:27:14: error: 'TX' was not declared in this scope

  #define LAT TX

              ^

C:\Users\vydaja\Downloads\RGBmatrixPanel_IDE-master\RGBmatrixPanel_IDE-master\examples\testshapes_16x32\testshapes_16x32.ino:45:37: note: in expansion of macro 'LAT'

 RGBmatrixPanel matrix(A, B, C, CLK, LAT, OE, false);

                                     ^

testshapes_16x32:26:13: error: 'D7' was not declared in this scope

  #define OE D7

             ^

C:\Users\vydaja\Downloads\RGBmatrixPanel_IDE-master\RGBmatrixPanel_IDE-master\examples\testshapes_16x32\testshapes_16x32.ino:45:42: note: in expansion of macro 'OE'

 RGBmatrixPanel matrix(A, B, C, CLK, LAT, OE, false);

                                          ^

exit status 1
'D6' was not declared in this scope

**Comment by FarooqIT** [comment]
Which arduino board you are using?

**Comment by pkourany** [comment]
@FarooqIT , this library is designed to the used with the Particle Photon, not an Arduino board.  If you want to use an Arduino board, the library you want to use is [here](https://github.com/adafruit/RGB-matrix-Panel).

**Comment by FarooqIT** [comment]
RGBmatrixPanel_IDE-master library is especially designed for arduino boards
and not for Particle Photon. If you want to use this library with Particle
Photon then you will have to modify the library according to pins maping of
Particle Photon.

**Comment by pkourany** [comment]
@FarooqIT, I responded to you when I should have responded to @vydarenyj !!  This library IS for Particle Photon, NOT for Arduino boards.  It is adapted to use different hardware timers with the SparkIntervalTimer library.

**Comment by vydarenyj** [comment]
Thanks for your help ... i try adafruit arduino library, but i use tihs library because i need chain of led matrix and i think with adafruit did not work ... PS sory for my bad engish

**Comment by FarooqIT** [comment]
But this library is specific to some described boards.

**Comment by FarooqIT** [comment]
And if you want to use this library for chain panels then use this library
on Raspberry boards
