### ISSUE TITLE
../SparkIntervalTimer/SparkIntervalTimer.h: No such file or directory

### ISSUE THREAD

**Issue by kornpow** [pkourany/RGBmatrixPanel_IDE#2]
I am trying to get the Photon to work with this library. Some errors I get are PI not being defined, which means something is weird with the Math library. Any word on maybe something I can do to help fix this for the Photon, I can code enough to potentially be able to help?

Veryfing code using this library in Particle Build fails with this error:

```
RGBmatrixPanel/RGBmatrixPanel.cpp:41:54: fatal error: ../SparkIntervalTimer/SparkIntervalTimer.h: No such file or directory
 #include "../SparkIntervalTimer/SparkIntervalTimer.h"
                                                      ^
```

**Comment by kornpow** [comment]
Looking at the other issue, since I have a Photon, if I compile locally should this work? The web IDE hides a whole lot that would be useful to have.

**Comment by pkourany** [comment]
I have neglected this library so my apology.  The updates for the Photon needed to wait for functionality that only came about in firmware v0.4.5 and later.  I will update the library shortly.  Thanks for reminding me!

**Comment by pkourany** [comment]
I just posted the updated library to the web IDE.

**Comment by kornpow** [comment]
I have made a PCB, with a level shifter from 3.3V to 5V in order to use this library. I am not using the default pins, but from my understanding the Photon isn't pinned out neatly by ports, so there is code to write to the proper pin. If I provide a schematic or something would you be willing to see if you can see any reason why this is not working?
In addition, since my board is using non-standard pinouts, I still have download all the code and compile, since I have to change the pin numbers in a file that isn't the .ino file. So maybe in the future move those pin setting #defines over to the .ino file so it can be changed when including the file?

**Comment by pkourany** [comment]
@sako0938, I am not sure why you are using a level shifter.  If you provide the schematic, I would be glad to look at it.  You are correct that the #defines are separated.  This is due to the fact that the library needs to stand alone.  It would be easy enough to move the pin assignments from the RGBMatrixPanel.h file to the user app (.ino) file.  I'll look into that.

**Comment by kornpow** [comment]
![ideaforgergbmatrix](https://cloud.githubusercontent.com/assets/3485377/11229035/ca933414-8d4e-11e5-94fa-1f589c816870.png)
So I assumed the display needed 5V logic, as it needed 5V input. The level shifter is set to be only a single direction, and it is a http://www.nxp.com/documents/data_sheet/74LVC4245A.pdf. Thanks for checking this out!

**Comment by pkourany** [comment]
I am driving the RGB panel directly without a level shifter.  Your design should work nonetheless.

**Comment by kornpow** [comment]
It'd be easy enough to remove the level shifter and pass the signal to the other side. I'll try a little bit more to get it working, and then I'll try it without.
