### ISSUE TITLE
Examples Crash Particle Photon

### ISSUE THREAD

**Issue by sallar** [pkourany/RGBmatrixPanel_IDE#4]
I tried running these examples on my Photon, it kind of works but:

- It's too fast, nothing is visible to human eye so it looks like a super fast animation with very bright colors
- Crashes Photon. Nothing can be flashed to the Photon OTA after a couple of seconds, so the Photon needs to be flashed using the command line tool: `particle serial flash tinker`

I have an idea for fixing it, (by adding `delay`), so I'll try that and send a PR if successful.

**Comment by pkourany** [comment]
@sallar, you are correct, putting a delay at the end of loop() will slow things down.  Try a delay(75) or a delay(150).

For the "crash", you may want to add `SYSTEM_THREAD(ENABLED)` at the top of the example code to allow the system firmware and user app to run in their own threads.

You may also want to look at the RGBPixelClock library in the Particle Build IDE for a fun project and a good usage example.

**Comment by sallar** [comment]
@pkourany Thanks. Good suggestions. 
Can we perhaps add something like this to the examples to prevent people from getting frustrated like me?:

``` cpp
void loop() {
  // ...
  #if defined (STM32F2XX) // Photon
    delay(75);
  #endif
}
```

Btw I tried running RGBPong project and it's running perfectly 🤗

**Comment by pkourany** [comment]
@sallar, or I just add the delays since the library is for Particle devices only anyway.

Thanks!

**Comment by pkourany** [comment]
I'll make the changes and post new version of library in Particle IDE.

**Comment by sallar** [comment]
Thanks man :) Cheers
