### ISSUE TITLE
How to make a 64x64 display of two 64x32 ?

### ISSUE THREAD

**Issue by RickardPettersson** [pkourany/RGBmatrixPanel_IDE#6]
I have got it to work to do a 128x32 display but whant it to be a 64x64 display any idea how?

**Comment by pkourany** [comment]
@RickardPettersson, as written, the code can only handle a single chain of displays.  To do a Nx64 would require another row of control lines OR some logic which "folds" the 128x32 into a 64x64.  This would simply be a logical remapping of display coordinates.  For example coordinates (64,64) on the logical display would be (128,32). At present, I have no plans to add this to the code though I'll definitely consider it.  A PR would also be great!

**Comment by pkourany** [comment]
@RickardPettersson, I may be able to post some updates for the 64x64 configuration over the next few days.  I don't have enough panels to test it so your help would be appreciated.  One thing is that you will need a long ribbon cable to connect the two corner screens diagonally.

**Comment by RickardPettersson** [comment]
i have already cable so i done this: https://youtu.be/vjZOVw5eFD4

But i whant it to be over each other to get 64x64, i think the cable i have is to short but if i see it works i can buy some other cable.

I can test your code if you commit some else i maybe can fix it my self when i get time.

**Comment by pkourany** [comment]
@RickardPettersson, I will post the changes and you can test when you get a chance.  I will also be posting an update to the library to adjust timing for longer displays so as not to lose OTA.  I noticed with more panels, there is overlap in timer interrupts and this will prevent OTA from working.

**Comment by RickardPettersson** [comment]
Sure let me know when you have some code to test.

**Comment by RickardPettersson** [comment]
Noiw i have 6 RGB Led Matrix Displays that are 64x32 pixels, so i put it together and trying changed your code but dont getting to work, its like i only can address 2 displayes 128x32 then after that its duplicate the same on the 4 other displays, see this video: https://www.youtube.com/watch?v=GrO0RxcmXv4

I  have tried write 384 as width but no differents on the width over 128.

**Comment by pkourany** [comment]
@RickardPettersson, the width is defined as a uint8_t meaning the maximum width is 255.  The library is really not designed to handle such wide displays though it could but with very poor refresh rate.  The more horizontal pixels that need to be drawn, the more time the ISR takes, reducing frame rate.  As it stands, using a wide array causes interrupts to missed.  This leads to problems with OTA.

**Comment by FarooqIT** [comment]
Hello dear RickardPettersson
I am working on a project which involves two 64x32 panel to be chained in 128x32 format using arduino mega , I don't k know how to get fulfilled this job . I need your help . please let me know how did you manage to chain them into 128x32.

**Comment by pkourany** [comment]
@FarooqIT, the Mega doesn't have enough RAM for the necessary display buffer.  At 128x32, the code needs 128*32*3 bytes (4 planes, packed) = 12,288 bytes.  Tod do double buffering, you would need 24,576 bytes.  The Mega only has 8,096 bytes of RAM.  The library in this repo is for use on a Particle Photon which has 60KB+ of RAM available to the user.

**Comment by FarooqIT** [comment]
Thanks a lot @pkourany for your quick and perfect reply. Now I understand why I can't supply the value 128 to the _width_ argument in 32x64 constructor of RGB matrix library. 
         Ok there is another thing I want to ask you @pkourany  that I want to use the pins of  PORTA of mega for some other purpose in my project but while you know that PORTA is used by RGB Matrix library for r, g, b.
        I want RGB_Matrix library to use other port say PORTL instead of PORTA so that PORTA be free for me. But I don't know what lines of code in RGB_matrix library  are to be changed to use PORTL. I will be very thankful to you If you explain to me the code to be changed. Sorry for my poor English , I am from Asia and we speak Urdu.

**Comment by pkourany** [comment]
@FarooqIT, as I previously said, this repo is for the Particle Photon, not Arduino.  Nonethless, the port pin assignments for the panel interface are specified in the RGBPanelMatrix.cpp file.  This is where you will need to modify the code in the Arduino version as well.

**Comment by FarooqIT** [comment]
@pkourany. Then on which forum I should discuss these with you ? , as I feel you only will be helpful to me . I want to discuss PORT manipulation further with you .

**Comment by pkourany** [comment]
@FarooqIT, the library based on t[his Adafruit library](https://github.com/adafruit/RGB-matrix-Panel).  Please do your research and read the contents of the files.  Specifically, in RGBMatrixPanel.cpp, you will find this comment:
```
#if defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
 // Arduino Mega is now tested and confirmed, with the following caveats:
 // Because digital pins 2-7 don't map to a contiguous port register,
 // the Mega requires connecting the matrix data lines to different pins.
 // Digital pins 24-29 are used for the data interface, and 22 & 23 are
 // unavailable for other outputs because the software needs to write to
 // the full PORTA register for speed.  Clock may be any pin on PORTB --
 // on the Mega, this CAN'T be pins 8 or 9 (these are on PORTH), thus the
 // wiring will need to be slightly different than the tutorial's
 // explanation on the Uno, etc.  Pins 10-13 are all fair game for the
 // clock, as are pins 50-53.
 #define DATAPORT PORTA
 #define DATADIR  DDRA
 #define SCLKPORT PORTB
```
I suggest you experiment with different ports.  That's as far as I can help you since I don't use this code or the Mega256.  If you have any questions, please post them on the [Adafruit Forum](https://forums.adafruit.com/).

**Comment by FarooqIT** [comment]
Ok thanks dear @pkourany.  I am working on it and will communicate with you if I face any ambiguity.
