### ISSUE TITLE
Scrolling text and no scrolling text at the same time ?

### ISSUE THREAD

**Issue by RickardPettersson** [pkourany/RGBmatrixPanel_IDE#8]
I like to show a "title" that alwasy should be show and a scrolling text below it.

When i testing the scrolltext example of the library and adding a still text that are fixed cursor place its blinking the text becouse of the fillScreen method.

Can i fill half the screen or own selected part of the screen?

**Comment by pkourany** [comment]
@RickardPettersson, if you look at the R[GBPixelClock_IDE](https://github.com/pkourany/RGBPixelClock_IDE) code, one of the clock "faces" called "marquee" creates two lines of separately scrolling text.  Take a look at the code to see how I did that.
